version: "3.9"
services:
  app:
    image: leoff00/diegobot:latest
    restart: on-failure
    networks:
      - diego_network
    ports:
      - 4000:4000

networks:
  diego_network:
    driver: bridge
