name: golangci
on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setting up golang 
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Setting up Docker Push
      run: DOCKER_BUILDKIT=1 docker image build -t diego_bot:$IMAGE_TAG . 
           docker tag diego_bot:$IMAGE_TAG leoff00/diego_bot:$IMAGE_TAG
           docker push leoff00/dieog_bot:$IMAGE_TAG
